name: rrule
description: "🔁 Recurrence rule parsing & calculation as defined in the iCalendar RFC"
version: 0.1.1
homepage: https://github.com/JonasWanke/rrule

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  basics: ^0.4.0
  collection: ^1.14.12
  meta: ^1.1.8
  pedantic: ^1.8.0+1
  time_machine:
    git:
      url: https://github.com/duytruong27/time_machine.git
      ref: HEAD

dev_dependencies:
  test: ^1.14.3
  test_coverage: ^0.4.1
